include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    dead_code: error
    unused_import: error
    unused_local_variable: error
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/firebase_options.dart"

linter:
  rules:
    always_declare_return_types: true
    always_use_package_imports: true
    avoid_print: true
    avoid_empty_else: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true
    unnecessary_this: true
    sort_constructors_first: true
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true
    require_trailing_commas: true
